GET https://tm6l5mqj-3000.brs.devtunnels.ms/api
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IllNN1B0eHRvbGliNEdqYk9SNEIzWiJ9.eyJpc3MiOiJodHRwczovL2Rldi04anY4bW9rMWJuaWtyMWVzLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2YTJjNDdhZTkzNWZkZTc2MGVkZmQzMzUiLCJhdWQiOlsiaHR0cHM6Ly90bTZsNW1xai0zMDAwLmJycy5kZXZ0dW5uZWxzLm1zIiwiaHR0cHM6Ly9kZXYtOGp2OG1vazFibmlrcjFlcy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzgxMzU5NTczLCJleHAiOjE3ODE0NDU5NzMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiJrOHlNRWU3ZkJiSFNLbzUxVDVhTndwV0lwdEpyUUdjQiIsInBlcm1pc3Npb25zIjpbXX0.X15Wvu0dE1QoBJcpJHj-PgNrnn2C8RVg4scRHgns3bZOyb9_IbehoIr1pF-NFV8DrT4LeCBCZAu28DBqeyldTln3ZrSmuDr2xRMRH9Zbwz5bkdmdMAP0rw_bbupA2S9i880xpjFvUW3GNWjtSKD7F8KzIeU-uNmepRnGDzEu8SgB3U3MG1c4nwuvUQl-W-t3B33OAhsKjqL4yNUsTXQLIBufBDWCNDzCXBM5-1fXgxy1ueZ5sXyS8v-NA3H9cKEkVUqs960xbKyQXCoLAhGZ92aZa5w2Qx4BOdqi6-P5y61bH1ZMANo5XSaj9fHfEg1EKuVFs1e-okyXgsHFShDdsQ

###
GET https://tm6l5mqj-3000.brs.devtunnels.ms/session/5493489553144@wa.gw.msging.net